# Generated by Django 5.2 on 2025-04-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(db_column='id_ruta', primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(db_column='nombre_ruta', max_length=100)),
                ('origen', models.CharField(db_column='origen', max_length=100)),
                ('destino', models.CharField(db_column='destino', max_length=100)),
                ('horario', models.TimeField(db_column='horario')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('correo_electronico', models.EmailField(db_column='correo_electronico', max_length=100)),
                ('contrasena', models.IntegerField(db_column='contrasena')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculos', models.AutoField(db_column='id_vehiculos', primary_key=True, serialize=False)),
                ('placa', models.CharField(db_column='placa', max_length=20)),
                ('empresa', models.IntegerField(db_column='empresa')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificaciones', models.AutoField(db_column='id_calificaciones', primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='calificacion')),
                ('comentario', models.TextField(db_column='comentario')),
                ('fecha', models.DateField(db_column='fecha')),
                ('id_ruta', models.ForeignKey(db_column='Rutas_id_ruta', on_delete=django.db.models.deletion.CASCADE, to='api_app.ruta')),
                ('id_usuario', models.ForeignKey(db_column='Usuarios_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_app.usuario')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='id_vehiculos',
            field=models.ForeignKey(db_column='Vehiculos_id_vehiculos', on_delete=django.db.models.deletion.CASCADE, to='api_app.vehiculo'),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(db_column='id_conductor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('licencia_conduccion', models.IntegerField(db_column='licencia_conduccion')),
                ('id_vehiculos', models.ForeignKey(db_column='Vehiculos_id_vehiculos', on_delete=django.db.models.deletion.CASCADE, to='api_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'Conductores',
            },
        ),
    ]
