# Generated by Django 5.2 on 2025-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo_electronico',
            new_name='correo',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.CharField(db_column='empresa', max_length=50),
        ),
    ]
