# Generated by Django 5.2 on 2025-04-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_correo_electronico_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='correo_electronico',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.IntegerField(db_column='empresa'),
        ),
    ]
