# Generated by Django 5.2.1 on 2025-05-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_column='fecha'),
        ),
    ]
