# Generated by Django 5.2 on 2025-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_correo_usuario_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.CharField(db_column='empresa', max_length=50),
        ),
    ]
