# Generated by Django 5.2.1 on 2025-05-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_calificacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
