# Generated by Django 5.2.1 on 2025-06-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50, unique=True)),
                ('descripcion', models.TextField(db_column='descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='Roles_id_rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.rol'),
        ),
    ]
