# Generated by Django 5.2.1 on 2025-06-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_rol_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(db_column='id_zona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('activa', models.BooleanField(db_column='activa', default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(db_column='id_tarifa', primary_key=True, serialize=False)),
                ('precio_base', models.DecimalField(db_column='precio_base', decimal_places=2, max_digits=10)),
                ('precio_km', models.DecimalField(db_column='precio_km', decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(db_column='activa', default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('actualizado_por', models.ForeignKey(db_column='Usuarios_id_actualizado_por', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zona_destino', models.ForeignKey(db_column='Zonas_id_destino', on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_destino', to='api_app.zona')),
                ('zona_origen', models.ForeignKey(db_column='Zonas_id_origen', on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_origen', to='api_app.zona')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'Tarifas',
                'unique_together': {('zona_origen', 'zona_destino')},
            },
        ),
    ]
