# Generated by Django 5.2.1 on 2025-06-04 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_zona_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(db_column='id_viaje', primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True, db_column='fecha_viaje')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('cancelado', 'Cancelado'), ('en_curso', 'En Curso')], db_column='estado', default='en_curso', max_length=20)),
                ('precio_final', models.DecimalField(db_column='precio_final', decimal_places=2, max_digits=10)),
                ('calificacion', models.OneToOneField(blank=True, db_column='Calificaciones_id_calificaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.calificacion')),
                ('id_ruta', models.ForeignKey(db_column='Rutas_id_ruta', on_delete=django.db.models.deletion.PROTECT, to='api_app.ruta')),
                ('id_usuario', models.ForeignKey(db_column='Usuarios_id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'Viajes',
                'ordering': ['-fecha_viaje'],
            },
        ),
        migrations.CreateModel(
            name='RutaFavorita',
            fields=[
                ('id_ruta_favorita', models.AutoField(db_column='id_ruta_favorita', primary_key=True, serialize=False)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True, db_column='fecha_agregada')),
                ('id_ruta', models.ForeignKey(db_column='Rutas_id_ruta', on_delete=django.db.models.deletion.CASCADE, to='api_app.ruta')),
                ('id_usuario', models.ForeignKey(db_column='Usuarios_id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Favorita',
                'verbose_name_plural': 'Rutas Favoritas',
                'db_table': 'RutasFavoritas',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('id_usuario', 'id_ruta')},
            },
        ),
    ]
