# Generated by Django 5.2.1 on 2025-06-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_viaje_rutafavorita'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionConductor',
            fields=[
                ('id_calificacion_conductor', models.AutoField(db_column='id_calificacion_conductor', primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='calificacion')),
                ('comentario', models.TextField(db_column='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('id_conductor', models.ForeignKey(db_column='Conductores_id_conductor', on_delete=django.db.models.deletion.CASCADE, to='api_app.conductor')),
                ('id_usuario', models.ForeignKey(db_column='Usuarios_id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_viaje', models.ForeignKey(db_column='Viajes_id_viaje', on_delete=django.db.models.deletion.CASCADE, to='api_app.viaje')),
            ],
            options={
                'verbose_name': 'Calificación de Conductor',
                'verbose_name_plural': 'Calificaciones de Conductores',
                'db_table': 'CalificacionesConductores',
                'ordering': ['-fecha'],
                'unique_together': {('id_viaje', 'id_usuario', 'id_conductor')},
            },
        ),
    ]
