# Generated by Django 5.2.1 on 2025-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_calificacionconductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaEmpresa',
            fields=[
                ('id_estadistica', models.AutoField(db_column='id_estadistica', primary_key=True, serialize=False)),
                ('id_empresa', models.IntegerField(db_column='id_empresa')),
                ('fecha', models.DateField(auto_now_add=True, db_column='fecha')),
                ('total_viajes', models.IntegerField(db_column='total_viajes', default=0)),
                ('viajes_completados', models.IntegerField(db_column='viajes_completados', default=0)),
                ('viajes_cancelados', models.IntegerField(db_column='viajes_cancelados', default=0)),
                ('ingresos_totales', models.DecimalField(db_column='ingresos_totales', decimal_places=2, default=0, max_digits=10)),
                ('calificacion_promedio', models.DecimalField(db_column='calificacion_promedio', decimal_places=2, default=0, max_digits=3)),
                ('pasajeros_transportados', models.IntegerField(db_column='pasajeros_transportados', default=0)),
                ('kilometros_recorridos', models.DecimalField(db_column='kilometros_recorridos', decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Estadística de Empresa',
                'verbose_name_plural': 'Estadísticas de Empresas',
                'db_table': 'EstadisticasEmpresas',
                'ordering': ['-fecha'],
                'unique_together': {('id_empresa', 'fecha')},
            },
        ),
    ]
