# Generated by Django 5.2.1 on 2025-06-04 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_estadisticaempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id_intento', models.AutoField(db_column='id_intento', primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(db_column='correo_electronico', max_length=254)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, db_column='fecha_intento')),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address')),
                ('exito', models.BooleanField(db_column='exito', default=False)),
                ('bloqueado', models.BooleanField(db_column='bloqueado', default=False)),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, db_column='fecha_desbloqueo', null=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'IntentosLogin',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='VersionSistema',
            fields=[
                ('id_version', models.AutoField(db_column='id_version', primary_key=True, serialize=False)),
                ('numero_version', models.CharField(db_column='numero_version', max_length=20, unique=True)),
                ('fecha_lanzamiento', models.DateTimeField(auto_now_add=True, db_column='fecha_lanzamiento')),
                ('tipo_cambio', models.CharField(choices=[('mayor', 'Cambio Mayor'), ('menor', 'Cambio Menor'), ('parche', 'Parche')], db_column='tipo_cambio', max_length=10)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('cambios', models.JSONField(db_column='cambios')),
                ('estado', models.CharField(choices=[('desarrollo', 'En Desarrollo'), ('pruebas', 'En Pruebas'), ('produccion', 'En Producción')], db_column='estado', default='desarrollo', max_length=20)),
                ('desarrollador', models.ForeignKey(db_column='Usuarios_id_desarrollador', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión del Sistema',
                'verbose_name_plural': 'Versiones del Sistema',
                'db_table': 'VersionesSistema',
                'ordering': ['-fecha_lanzamiento'],
            },
        ),
    ]
