# Generated by Django 5.2.1 on 2025-06-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_intentologin_versionsistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id_pqrs', models.AutoField(db_column='id_pqrs', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], db_column='tipo', max_length=20)),
                ('asunto', models.CharField(db_column='asunto', max_length=200)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], db_column='estado', default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_respuesta', models.DateTimeField(blank=True, db_column='fecha_respuesta', null=True)),
                ('respuesta', models.TextField(blank=True, db_column='respuesta', null=True)),
                ('id_usuario', models.ForeignKey(db_column='Usuarios_id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('respondido_por', models.ForeignKey(blank=True, db_column='Usuarios_id_respondido_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'PQRS',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
