# Generated by Django 5.2.1 on 2025-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, db_column='fecha_vencimiento_licencia', null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_soat',
            field=models.DateField(blank=True, db_column='fecha_vencimiento_soat', null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_tecnomecanica',
            field=models.DateField(blank=True, db_column='fecha_vencimiento_tecnomecanica', null=True),
        ),
    ]
