# Generated by Django 5.2.1 on 2025-06-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_alter_conductor_licencia_conduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='Roles_id_rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.rol'),
        ),
    ]
