# Generated by Django 5.2.1 on 2025-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_crear_roles_iniciales'),
        ('api_app', '0015_alter_usuario_rol'),
    ]

    operations = [
    ]
