# Generated by Django 4.2.10 on 2025-06-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_merge_20250605_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='id_vehiculos',
            field=models.ForeignKey(blank=True, db_column='Vehiculos_id_vehiculos', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.vehiculo'),
        ),
    ]
