# Generated by Django 4.2.10 on 2025-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_alter_conductor_id_vehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa',
            field=models.CharField(db_column='empresa', max_length=100),
        ),
    ]
