# Generated by Django 4.2.10 on 2025-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_alter_vehiculo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='zona_destino',
            field=models.CharField(db_column='zona_destino', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='zona_origen',
            field=models.CharField(db_column='zona_origen', max_length=100),
        ),
    ]
